version: '2'
services:

  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
     - "3306:3306"
    volumes:
       - "/home/mysql/:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: cnix@123456


  portal-x:
    image: node:12.18.2
    container_name: portal-x
    working_dir: /var/www/html/
    volumes:
      - "/home/webapps/portal-x:/var/www/html"
    ports:
      - "1985:1985/tcp"
    tty: true
    command: >
      sh -c "npm start "


  cnix-boss-portal:
    image: node:12.18.2
    container_name: cnix-boss-portal
    working_dir: "/var/www/html"
    volumes:
      - "/home/webapps/cnix-boss-portal/:/var/www/html"
    ports:
     - "8503:8503/tcp"
    tty: true
    command: >
      sh -c "npm start "


  vue-dingding:
    image: node:12.18.2
    container_name: vue-dingding
    privileged: true
    working_dir: "/var/www/html"
    volumes: 
       - "/home/webapps/Dingtalk-vue/:/var/www/html"
    depends_on: 
       -  mysql
    ports:
     - "3000:3000/tcp" 
    tty: true
    command: >
      sh -c "npm start "



  api-x:
    image: apache2-php7-x
    container_name: api-x
    ports:
     - "1984:80"
    volumes:
      - "/home/webapps/api-x/:/var/www/html"
    tty: true


  cnix-boss-portal-api:
    image: apache2-php7-x
    container_name: cnix-boss-portal-api
    ports:
     - "8502:80"
    volumes:
      - "/home/webapps/cnix-boss-portal-api/:/var/www/html"
    tty: true

  md-admin:
    image: apache2-php7-x
    container_name: md-admin
    privileged: true
    volumes: 
       - "/home/webapps/MD-admin/:/var/www/html"
    depends_on: 
       -  mysql
    ports:
     - "6800:80" 
    tty: true


  md-api:
    image: apache2-php7-x
    container_name: md-api
    privileged: true
    volumes: 
       - "/home/webapps/MD-api/:/var/www/html"
       - "/home/cnixdockers/docker-apache-php7/ssl/etc/letsencrypt/:/etc/letsencrypt"
       - "/home/cnixdockers/docker-apache-php7/www.chilink.com.cn.conf:/etc/apache2/sites-available/www.chilink.com.cn.conf"

    depends_on: 
       -  mysql
    ports:
     - "443:443" 
    stdin_open: true
    tty: true


  nanx-api:
    image: apache2-php7-x
    container_name: nanx-api
    privileged: true
    volumes: 
       - "/home/webapps/nanx-api/:/var/www/html"

    depends_on: 
       -  mysql
    ports:
     - "8964:80" 
    stdin_open: true
    tty: true


  md-socket:
    image: apache2-php7-x
    container_name: md-socket
    ports:
      - "9000:443"
    volumes:
       - "/home/webapps/MD-socket/src/:/var/www/html"
       - "/home/cnixdockers/docker-apache-php7/ssl/etc/letsencrypt/:/etc/letsencrypt"
       - "/home/cnixdockers/docker-apache-php7/socket-www.chilink.com.cn.conf:/etc/apache2/sites-available/socket-www.chilink.com.cn.conf"       
       - "/home/webapps/MD-socket/supervisord-apache/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf"
       - "/home/webapps/MD-socket/init.sh:/usr/local/bin/init.sh"
    tty: true
    working_dir: "/var/www/html" 


  custportal-rootui-react:
    image: node:12.18.2
    container_name: custportal-rootui-react
    working_dir: /var/www/html/rootui-react
    volumes:
      - "/home/webapps/custportal-rootui-react:/var/www/html"
    ports:
      - "5500:5500/tcp"
    tty: true
    command: >
      sh -c "npm start "



  dingtalk-api:
    image: apache2-php7-x
    container_name: dingtalk-api
    privileged: true
    volumes: 
       - "/home/webapps/Dingtalk-api-php/:/var/www/html"
    depends_on: 
       -  mysql
    ports:
     - "8905:80" 
    tty: true

