FROM ubuntu:14.04
MAINTAINER Nicholas Istre <nicholas.istre@e-hps.com>

# Setup environment
ENV DEBIAN_FRONTEND noninteractive

# Update sources
ADD sources.list  /etc/apt/sources.list
RUN apt-get update -y  &&  rm -rf /var/lib/apt/lists/*

RUN echo "Asia/Chongqing" > /etc/timezone
RUN sudo dpkg-reconfigure -f noninteractive tzdata
